controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_sortie_voir:
    path: '/sorties/voir/{id}'
    controller: 'App\Controller\SortieController::voir'

app_sorties_lister:
    path: /sorties
    controller: 'App\Controller\SortiesController::lister'